// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtobufObjectfactory

#region Designer generated code

using DotBPE.Protobuf;
using Google.Protobuf.Reflection;
using System.Collections.Generic;


namespace SlideApp
{
    public class ProtobufDescriptorFactory : IProtobufDescriptorFactory
    {
        private static Dictionary<string, MessageDescriptor> DCACHE = new Dictionary<string, MessageDescriptor>();

        static ProtobufDescriptorFactory()
        {
            
            DCACHE.Add("10000|1|1",  HelloReq.Descriptor); //请求
            DCACHE.Add("10000|1|2",  HelloRes.Descriptor); //响应
            
            DCACHE.Add("10000|2|1",  HelloReq.Descriptor); //请求
            DCACHE.Add("10000|2|2",  HelloRes.Descriptor); //响应
            
            
        }

        public MessageDescriptor GetRequestDescriptor(int serviceId, int messageId)
        {
            string key = $"{serviceId}|{messageId}|1";
            if (DCACHE.ContainsKey(key))
            {
                return DCACHE[key];
            }
            return null;
        }

        public MessageDescriptor GetResponseDescriptor(int serviceId, int messageId)
        {
            string key = $"{serviceId}|{messageId}|2";
            if (DCACHE.ContainsKey(key))
            {
                return DCACHE[key];
            }
            return null;
        }
    }
}

#endregion Designer generated code